# Параметри ініціалізації програми "Фургон кави"

# Вантажний об'єм фургона, л
van.capacity.liters=18
# Сума, на яку можна закупити каву, грн
van.budget=5600

# Діапазон параметрів якості для пошуку товарів у фургоні (оцінки 0-10)
search.aroma.min=7
search.aroma.max=10
search.acidity.min=5
search.acidity.max=9
search.body.min=5
search.body.max=8
